{
  "debug": true,
  "server": {
    "address": ":8080",
    "timeout": "30",
  },
  "context":{
    "timeout":2
  },
  "database": {
    "host": "localhost",
    "port": "3306",
    "user": "user",
    "pass": "password",
    "name": "article"
  }

}
